// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdMFhVsptHcOg8bRi0S7eEvYZmKXCVlPc',
    appId: '1:582861652028:web:c8b20403b4946e0e6b8339',
    messagingSenderId: '582861652028',
    projectId: 'foodpharma-e2be4',
    authDomain: 'foodpharma-e2be4.firebaseapp.com',
    storageBucket: 'foodpharma-e2be4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eq4Zy2aEmqg5knxEkGf-dj6Am_clE3E',
    appId: '1:582861652028:android:c5b6232cc74cbb9c6b8339',
    messagingSenderId: '582861652028',
    projectId: 'foodpharma-e2be4',
    storageBucket: 'foodpharma-e2be4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgDrKZjLbL-Jx_mqGAlZFPrikoKxurtY',
    appId: '1:582861652028:ios:2789347593070f746b8339',
    messagingSenderId: '582861652028',
    projectId: 'foodpharma-e2be4',
    storageBucket: 'foodpharma-e2be4.firebasestorage.app',
    iosBundleId: 'com.ankit14.camera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgDrKZjLbL-Jx_mqGAlZFPrikoKxurtY',
    appId: '1:582861652028:ios:2789347593070f746b8339',
    messagingSenderId: '582861652028',
    projectId: 'foodpharma-e2be4',
    storageBucket: 'foodpharma-e2be4.firebasestorage.app',
    iosBundleId: 'com.ankit14.camera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdMFhVsptHcOg8bRi0S7eEvYZmKXCVlPc',
    appId: '1:582861652028:web:4c905df7cb1ad9566b8339',
    messagingSenderId: '582861652028',
    projectId: 'foodpharma-e2be4',
    authDomain: 'foodpharma-e2be4.firebaseapp.com',
    storageBucket: 'foodpharma-e2be4.firebasestorage.app',
  );
}
